services:
  - type: web
    name: sudoku-bot
    env: node
    plan: starter
    buildCommand: npm install && npx puppeteer browsers install chrome
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production